### ISSUE TITLE
devel branch compilation failure on RHEL8: error: 'class cvmfs::MsgRpc' has no member named 'ByteSizeLong'

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#4432]
I'm getting a compilation failure on RHEL8 with the latest devel branch:

```
/scratch/RPMBUILD/BUILD/cvmfs-2.15.0/cvmfs/cache_transport.cc: In member function 'void CacheTransport::SendFrame(CacheTransport::Frame*)':
/scratch/RPMBUILD/BUILD/cvmfs-2.15.0/cvmfs/cache_transport.cc:528:37: error: 'class cvmfs::MsgRpc' has no member named 'ByteSizeLong'; did you mean 'ByteSize'?
   const size_t byte_size = msg_rpc->ByteSizeLong();
                                     ^~~~~~~~~~~~
                                     ByteSize
```

This code was introduced in https://github.com/cvmfs/cvmfs/pull/4409#discussion_r3960314632

**Comment by vvolkl** [comment]
Right, that might have inadvertantly bumped the required protobuf version. Setting a correct required version in CMake should be the easiest fix.
