### PR TITLE
Make mockfuse test compatible with libfuse 3.17+

### PR DESCRIPTION
**Pull request by andrey-utkin**
[As I reported earlier](https://github.com/cvmfs/cvmfs/issues/4398#issuecomment-5223889172), it didn't build with libfuse 3.17 or later:

    /usr/bin/ld: CMakeFiles/cvmfs_unittests_mockfuse.dir/t_cvmfs.cc.o: in function `cvmfs::cvmfs_open(fuse_req*, unsigned long, fuse_file_info*)':
    /usr/local/src/cvmfs/cvmfs/cvmfs.cc:1381:(.text+0x3d66): undefined reference to `fuse_passthrough_open'
    /usr/bin/ld: CMakeFiles/cvmfs_unittests_mockfuse.dir/t_cvmfs.cc.o: in function `cvmfs::cvmfs_release(fuse_req*, unsigned long, fuse_file_info*)':
    /usr/local/src/cvmfs/cvmfs/cvmfs.cc:1712:(.text+0x63ce): undefined reference to `fuse_passthrough_close'
    clang++: error: linker command failed with exit code 1 (use -v to see invocation)

Also there was NULL dereference in cvmfs_open() code (from me actually)

### CODE REVIEW

**Review by vvolkl — APPROVED** [review]
Thanks for the patch! Looks good to me. Yes, the passthrough PR also introduced another issue in cvmfs_destroy ( https://github.com/cvmfs/cvmfs/issues/4438 ). @christge-sft is looking into the fix for that.
